import { ReactNode } from "react";
import SideBarLayout from "../components/SideBarLayout";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Documentation",
  icons: {
    icon: "/e.svg",
  },
  description: "Generated by med elhaissan ",
};

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <div className="flex flex-col md:flex-row h-screen font-mono tracking-[-.01em] ">
      <SideBarLayout />

      <main className="md:flex-1 w-full overflow-x-hidden h-screen p-4 ">
        {children}
      </main>
    </div>
  );
}
